### ISSUE TITLE
System.ObjectDisposedException: The object has been closed. after a few seconds

### ISSUE THREAD

**Issue by thetestgame** [sharpbrick/powered-up#189]
After a few seconds and one command being sent to a Lego hub it abruptly closes the connection. Is there a heartbeat step that needs to occur? This is currently guaranteed to happen every time I try with my current codebase.

```
System.ObjectDisposedException: The object has been closed. (0x80000013)
   at SharpBrick.PoweredUp.WinRT.WinRTPoweredUpBluetoothCharacteristic.WriteValueAsync(Byte[] data)
   at SharpBrick.PoweredUp.Bluetooth.BluetoothKernel.SendBytesAsync(Byte[] data)
   at SharpBrick.PoweredUp.Protocol.LegoWirelessProtocol.SendMessageAsync(LegoWirelessMessage message)
   at SharpBrick.PoweredUp.Protocol.ILegoWirelessProtocolExtensions.SendMessageReceiveResultAsync[TResultMessage](ILegoWirelessProtocol self, LegoWirelessMessage message, Func`2 filter)
   at SharpBrick.PoweredUp.Protocol.ILegoWirelessProtocolExtensions.SendPortOutputCommandAsync(ILegoWirelessProtocol self, PortOutputCommandMessage message)
   at SharpBrick.PoweredUp.BasicMotor.StartPowerAsync(SByte power)
   ```

**Comment by tthiery** [comment]
In the protocol there is no concept of heartbeat. The hubs have a very strange initial connection mode but aside of that it is a very simple protocol on the frame layer.

**Comment by tthiery** [comment]
This is a bit strange considering that StartPower is one of the most basic commands.

**Comment by tthiery** [comment]
I guess this is the hub shutting down. Question is why:

- command wrong encoded: i do not believe so
- too many commands at once (have you tried with throttling/waiting in between or is your code multi-threaded
- do you have esoteric BT hardware? Does it work otherwise/default Lego app?

**Comment by thetestgame** [comment]
This is repeatable after sending only one command after the initial connect call. Also the Hubs I've tested with work fine otherwise with the controller or the Lego app.

**Comment by tthiery** [comment]
Have you had the chance to test it on another device? I have no trains, it worked last time I used it (tm) and right now I am in an actual train so hard time supporting you 😂

**Comment by tthiery** [comment]
Creating a trace file would be helpful. I could verify the correct encoding there and check the exact place the thing fails

**Comment by thetestgame** [comment]
> Have you had the chance to test it on another device? I have no trains, it worked last time I used it (tm) with a technic hub and motor and right now I am in an actual train so hard time supporting you 😂

I have not. I'll try that later today.

> Creating a trace file would be helpful. I could verify the correct encoding there and check the exact place the thing fails

Do you have a preferred tool for trace files?

**Comment by thetestgame** [comment]
Additional bit of information. It seems to disconnect/stop on its own regardless if I send any new commands. Also sometimes it keeps working flawlessly but its rare. When the abrupt stop happens the light on the hub is still on like its connected but the object has been disposed from .NET.

**Comment by tthiery** [comment]
Which Hub ist it exactly? The train one with the motors or the default Lego two port hub?

**Comment by thetestgame** [comment]
I'm using the Lego two port hubs from the RC trains.

**Comment by tthiery** [comment]
I do not have any and I do not remember special behavior for them. They are a late product like the technic hubs.
